db:
  host: "127.0.0.1"
  port: 27017
  database: "mailcatcher"
smtp:
  ip: '127.0.0.1'
  port: 1025
http:
  ip: '127.0.0.1'
  port: 1080
password: ~
verbose: false
token_secret: 'XAiOjJKv1QiLCJhb'
users:
  -
    name: 'test1'
    password: '123'
    owners: ~ # allowed all messages
  -
    name: 'test2'
    password: '123'
    owners: [] # disallow all messages
  -
    name: 'test3'
    password: '123'
    owners: ['foo', ''] # allowed 'foo' owner and messages with no owner
