db:
  host: "127.0.0.1"
  port: 27017
  database: "mailcatcher"
smtp:
  ip: '0.0.0.0'
  port: 1025
http:
  ip: '0.0.0.0'
  port: 1080
password: '123'
verbose: false
token_secret: 'XAiOjJKv1QiLCJhb'
users:
  -
    name: 'test1'
    password: '123'
    folders: '!all' # allowed all messages
  -
    name: 'test2'
    password: '123'
    folders: [] # disallow all messages
  -
    name: 'test3'
    password: '123'
    folders: ['foo'] # allowed messages inside 'foo' folder
  -
    name: 'test4'
    password: '123'
    folders: ['!unassigned', 'boo'] # allowed unassigned messages plus messages inside 'boo' folder
